name: JavaScript

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  syntax:
    name: "Check Syntax"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22
          - 23
          - 24
    steps:
      - name: Set up node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v5
      - run: echo "::add-matcher::.github/javascript-syntax.json"
      - name: Remove files to be ignored
        run: |
          true
      - run: |
          ! find dist/ -type f -name '*.js' -exec node -c '{}' \; 2>&1 \
            |awk 'BEGIN {m=0} /(.js):[0-9]+$/ {m=1; printf "%s - ",$0} m==1 && /^SyntaxError/ { m=0; print }' \
            |sed "s@$(pwd)@.@" \
            |grep '^'
