name: Release

on:
  push:
    tags: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.com/"
      - run: npm ci
      - name: Read package.json
        id: package
        uses: RadovanPelka/github-action-json@main
        with:
          path: "package.json"
      - name: Remove old builds
        run: |
          rm -rf *.tgz
      - name: Publish to npmjs.com
        if: steps.package.outputs.private == '' || steps.package.outputs.private == 'false' || steps.package.outputs.private == false
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create package
        run: |
          npm pack
      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.tgz"
          fail_on_unmatched_files: true
