name: TypeScript

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tsc:
    name: "TSC"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22
          - 23
          - 24
    steps:
      - uses: actions/checkout@v5
      - name: Set up node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: |
          npx tsc --noEmit
  eslint:
    name: "eslint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "npm"
      - run: npm install
      - run: npx eslint .
